spring:
  application:
    name: court-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration,classpath:db/seed

management:
  endpoint:
    health:
      show-components: always

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}]"
